/* c/src/main.c
 * demo program for the S4D galaxy classifier
 * loads model weights and runs inference on a single input image
 *
 * usage:
 *   ./main <weights.bin> <image.bin>
 *
 * weights.bin : model_weights.bin generated by combine_weights.py
 * image.bin   : flat float32 binary file
 *               RGB:       64*64*3 = 12288 floats in (H,W,C) layout
 *               grayscale: 64*64*1 = 4096  floats in (H,W,1) layout
 *
 * output:
 *   prints class probabilities and predicted class label */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/nn.h"

/* class names matching the galaxy zoo dataset categories */
static const char* CLASS_NAMES[NUM_CLASSES] = {
    "Smooth",
    "Disk",
    "Edge-on",
    "Irregular"
};

/*
 * load_image -- loads a flat float32 binary image file into buffer
 * n is the number of floats to read (4096 for grayscale, 12288 for RGB)
 * exits if file cannot be opened or has wrong size */
static void load_image(const char* path, float* buffer, size_t n) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        printf("ERROR: Cannot open image file: %s\n", path);
        exit(1);
    }
    size_t got = fread(buffer, sizeof(float), n, f);
    fclose(f);
    if (got != n) {
        printf("ERROR: Expected %zu floats but got %zu from %s\n",
               n, got, path);
        exit(1);
    }
}

/*
 * argmax -- returns index of largest value in array
 * used to find the predicted class from probabilities */
static int argmax(const float* arr, int n) {
    int best = 0;
    for (int i = 1; i < n; i++) {
        if (arr[i] > arr[best]) best = i;
    }
    return best;
}

int main(int argc, char** argv) {

    /* check command line arguments */
    if (argc < 3) {
        printf("Usage: %s <weights.bin> <image.bin>\n", argv[0]);
        printf("  weights.bin : model_weights.bin from combine_weights.py\n");
        printf("  image.bin   : float32 binary image (12288 floats for RGB)\n");
        return 1;
    }

    const char* weights_path = argv[1];
    const char* image_path   = argv[2];

    /* load model weights from binary file
     * this reads all parameters into static arrays in nn.c
     * must be called before model_forward */
    if (load_model_weights(weights_path) != 0) {
        printf("ERROR: Failed to load model weights\n");
        return 2;
    }

    /* load input image
     * we assume RGB (3 channels) by default
     * if your model was trained on grayscale change C=3 to C=1
     * and load only 4096 floats */
    int C = 3;
    int image_size = IMG_SIZE * C;  /* 4096 * 3 = 12288 for RGB */

    /* static buffer for input image -- no malloc */
    static float image[IMG_SIZE * 3];
    memset(image, 0, sizeof(image));

    printf("Loading image from: %s\n", image_path);
    load_image(image_path, image, image_size);
    printf("Image loaded (%d floats, %s)\n",
           image_size, C == 3 ? "RGB" : "grayscale");

    /* run inference -- this chains all 11 steps in model_forward */
    printf("\nRunning inference...\n");
    float probs[NUM_CLASSES];
    model_forward(image, C, probs);

    /* print results in the format specified by the milestone spec */
    printf("\nClass Probabilities:\n");
    for (int i = 0; i < NUM_CLASSES; i++) {
        printf("  Class %d (%s): %.4f\n", i, CLASS_NAMES[i], probs[i]);
    }

    int predicted = argmax(probs, NUM_CLASSES);
    printf("\nPredicted Class: %d (%s)\n",
           predicted, CLASS_NAMES[predicted]);

    return 0;
}